server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///dubbo_class
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: class_service
  registry:
    address: zookeeper://192.168.59.131:2181
  protocol:
    port: 20881


